Repository CeoFred/bonpay-ui, pull requests merged in 2022-10, with the labels that each got.

#11 Setup .github folder with a pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest-accepted

#9 Update index.html
  public/index.html
Labels: hacktoberfest-accepted

#25 Web3 integration
  .all-contributorsrc
  CONTRIBUTING.md
  LICENSE.md
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/Pages/Home/index.jsx
  src/Providers/Message.Listener.js
  src/Providers/Web3.provider.js
  src/assets/images/logo.png
  src/components/Button/button.styles.css
  src/components/Button/index.js
  src/config/chain.js
  src/container/ErrorBoundary.js
  src/container/Layout.js
  src/container/Wrapper.js
  src/copy.png
  src/index.js
  src/open.png
  src/popup.html
  src/reducers/network/networkSlice.js
  src/reducers/network/selector.js
  src/reducers/wallet/walletSlice.js
  src/router.js
  src/routes/index.js
  src/store/index.js
  src/theme/index.chakra-ui.js
  src/utils/helpers.js
Labels: hacktoberfest, hacktoberfest-accepted

#26 Development
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/Pages/Home/index.jsx
  src/Providers/Message.Listener.js
  src/Providers/Web3.provider.js
  src/assets/images/logo.png
  src/components/Button/button.styles.css
  src/components/Button/index.js
  src/config/chain.js
  src/container/ErrorBoundary.js
  src/container/Layout.js
  src/container/Wrapper.js
  src/index.js
  src/reducers/network/networkSlice.js
  src/reducers/network/selector.js
  src/reducers/wallet/walletSlice.js
  src/router.js
  src/routes/index.js
  src/store/index.js
  src/theme/index.chakra-ui.js
  src/utils/helpers.js
Labels: hacktoberfest-accepted

#27 formatted
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/Pages/Home/index.jsx
  src/Providers/Message.Listener.js
  src/Providers/Web3.provider.js
  src/components/Button/button.styles.css
  src/components/Button/index.js
  src/config/chain.js
  src/container/ErrorBoundary.js
  src/container/Layout.js
  src/container/Wrapper.js
  src/index.css
  src/index.js
  src/popup.html
  src/reducers/network/networkSlice.js
  src/reducers/network/selector.js
  src/reducers/wallet/walletSlice.js
  src/reportWebVitals.js
  src/router.js
  src/routes/index.js
  src/setupTests.js
  src/store/index.js
  src/theme/index.chakra-ui.js
  src/utils/helpers.js
Labels: hacktoberfest, hacktoberfest-accepted

#28 added eslint
  .eslintrc.js
  .prettierrc.json
  package.json
  src/Providers/Web3.provider.js
Labels: hacktoberfest, hacktoberfest-accepted

#29 Version 1 Release
  src/App.css
  src/App.js
  src/Pages/Home/index.jsx
  src/Providers/Message.Listener.js
  src/Providers/Web3.provider.js
  src/assets/icons/open.png
  src/config/chain.js
  src/container/Layout.js
  src/open.png
  src/popup.html
  src/reducers/network/networkSlice.js
  src/reducers/transaction/selector.js
  src/reducers/transaction/transactionSlice.js
  src/reducers/wallet/walletSlice.js
  src/store/index.js
Labels: v1
